easy_admin:
    site_name: En première ligne

    design:
        menu:
            - { route: 'homepage', label: 'Back to the website', icon: 'home' }
            - { route: 'security_logout', label: 'Log out', icon: 'sign-out' }

            - { label: 'Matchings' }
            - { route: 'admin_statistics', label: 'Statistics', icon: 'chart-bar' }
            - { route: 'admin_matches', label: 'Matches', icon: 'check' }
            - { route: 'admin_match_history', label: 'History', icon: 'history' }
            - { entity: 'Helper', label: 'Helpers', icon: 'users' }
            - { entity: 'HelpRequest', label: 'Help requests', icon: 'handshake-o' }
            - { entity: 'BlockedMatch', label: 'Blocked matches', icon: 'times' }
            - { route: 'admin_export_helpers', label: 'Export helpers', icon: 'cloud-download', target: '_blank' }

    entities:
        Helper:
            class: App\Entity\Helper
            disabled_actions: ['show', 'new', 'edit']
            list:
                title: Helpers
                max_results: 100
                sort: ['createdAt', 'DESC']
                actions:
                    - { name: 'delete', template: 'admin/actions/delete_helper.html.twig' }
                fields:
                    - id
                    - zipCode
                    - firstName
                    - lastName
                    - email
                    - canBabysit
                    - canBuyGroceries
                    - createdAt

        HelpRequest:
            class: App\Entity\HelpRequest
            disabled_actions: ['show', 'new', 'edit']
            list:
                title: Help requests
                max_results: 100
                sort: ['createdAt', 'DESC']
                fields:
                    - id
                    - zipCode
                    - helpType
                    - firstName
                    - lastName
                    - email
                    - { property: 'isMatched', type: 'boolean', label: 'Has a match?' }
                    - finished
                    - createdAt

        BlockedMatch:
            class: App\Entity\BlockedMatch
            disabled_actions: ['show', 'new', 'edit']
            list:
                title: Blocked matches
                max_results: 100
                sort: ['createdAt', 'DESC']
                fields:
                    - id
                    - owner
                    - helper.firstName
                    - helper.lastName
                    - createdAt
